% delta time for simulation. Will be updated in main loop
global dt;
dt = 0.05;


% Index of pid_data structures. Ex "pid_data(pd_index.g_roll)"
pd_index = struct(...
    'g_roll',     1,...     % gyro Roll
    'g_pitch',    2,...
    'g_yaw',      3,...
    'a_roll',     4,...     % acc roll
    'a_pitch',    5,...
    'compass',    6,...     % heading
    'height',     7);       % altitude

global pid_data;
pid_data = struct(... %g_roll | g_pitch | g_yaw | a_roll | a_pitch | compass | height  
    'Kp',             {1,       1,        1,      1,       1,        1,        1},...
    'Ki',             {0,       0,        0,      0,       0,        0,        0},...
    'Kd',             {0,       0,        0,      0,       0,        0,        0},...
    'integral',       {0,       0,        0,      0,       0,        0,        0},...
    'i_max',          {100,     100,      100,    100,     100,      100,      100},...
    'e',              {0,       0.1,        0,      0,       0,        0,        0},...
    'prev_e',         {0,       0,        0,      0,       0,        0,        0});

% Array of setpoints. Indexed by for ex "set_points(pd_index.roll)"
set_points  = zeros(1,length(fieldnames(pd_index)));
% Array of sensor data
states      = zeros(1,length(fieldnames(pd_index)));
% Array of contro outputs
outputs     = zeros(1,length(fieldnames(pd_index)));
